language: cpp
dist: xenial
os:
- linux

services:
- xvfb
  
addons:
  apt:
    packages:
    # lxml dependencies.
    - libxml2-dev
    - libxslt1-dev
    # pyttsx dependencies.
    - libespeak1
    # SciPy dependencies.
    - libatlas-base-dev
    - libxkbcommon-x11-0
    - build-essential
    - git
    - libxkbcommon-x11-dev
    - libssl-dev
    - liblua5.2-dev
    - libgl1-mesa-dev
    - wget
    - libfontconfig1
    - libdbus-1-dev
    - libglu1-mesa-dev
    - g++-4.8
    - gcc-4.8
    - cmake
  
sudo: required

env:
    - QT_CI_PACKAGES=qt.qt5.5132.gcc_64,qt.qt5.5132.qtwebengine PATH="$TRAVIS_BUILD_DIR/Qt/5.13.2/gcc_64/bin:${PATH}" VERBOSE=1
    
compiler: gcc

before_install:
 - pwd
 - cd /home/travis/build/mjoppich/bioGUI
 

before_script:
  - git clone https://github.com/benlau/qtci.git
  - source qtci/path.env
  - install-qt 5.13.2
  - mkdir build
  - cd build
  - cmake ..

script: make
