language: cpp
dist: xenial
os:
- linux

services:
- xvfb
  
addons:
  apt:
    packages:
    # lxml dependencies.
    - libxml2-dev
    - libxslt1-dev
    # pyttsx dependencies.
    - libespeak1
    # SciPy dependencies.
    - libatlas-base-dev
    - libxkbcommon-x11-0
    - build-essential
    - git
    - libxkbcommon-x11-dev
    - libssl-dev
    - liblua5.2-dev
    - libgl1-mesa-dev
    - wget
    - libfontconfig1
    - libdbus-1-dev
    - libglu1-mesa-dev
    - g++-4.8
    - gcc-4.8
    - cmake
    - qtbase5-dev
    - qtdeclarative5-dev
    - libqt5webkit5-dev
    - libsqlite3-dev
    - qt5-default
    - qttools5-dev-tools
    - libqt5xmlpatterns5-dev
  
sudo: required
    
compiler: gcc

before_install:
 - pwd
 - cd /home/travis/build/mjoppich/bioGUI
 

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
