language: cpp

dist: trusty
sudo: required

compiler: gcc

before_install:
 - pwd
 - sudo apt-get -qq update
 - sudo apt-get install -y build-essential git libssl-dev liblua5.2-dev libgl1-mesa-dev wget libfontconfig1 libdbus-1-dev libglu1-mesa-dev g++-4.8 gcc-4.8 cmake
 - cd ~
 - pwd
 - wget -O qt-opensource.run http://download.qt.io/official_releases/qt/5.14/5.14.2/qt-opensource-linux-x64-5.14.2.run
 - chmod u+x qt-opensource.run
 - sudo ./qt-opensource.run --verbose -platform minimal --script /home/travis/build/mjoppich/bioGUI/silent_qt_install.qs
 - ls /opt/Qt5.14.2/
 - export PATH=/opt/Qt5.14.2/5.14.2/gcc_64/bin/:$PATH
 - cd /home/travis/build/mjoppich/bioGUI
 

before_script:
  - mkdir build
  - cd build
  - PATH=/opt/Qt5.14.2/5.14.2/gcc_64/bin/:$PATH cmake ..

script: make
